### ISSUE TITLE
Update tox and CI configurations

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/sdx-lc#70]
Came across two problems at https://github.com/atlanticwave-sdx/sdx-lc/actions/runs/3699674951:

- [ ] GitHub is deprecating `set-output` command, used by our pip caching step.
- [ ] A new tox release has broken backward compatibility with older `tox.ini` directives.
- [ ] Also update coveralls.io reporting configuration while we're at it.

**Comment by sajith** [comment]
Fixed in #72.
