### ISSUE TITLE
Release sdx-lc 2.0.0

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/sdx-lc#92]
- [ ] Write changelog entries
- [ ] Bump up version 2.0.0 in setup.py
- [ ] Update README
- [ ] Add a git tag for the release 
- [ ] Make a GitHub release
