### ISSUE TITLE
Environment clean up

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/sdx-lc#94]
Similar to https://github.com/atlanticwave-sdx/sdx-controller/issues/162.  Would be nice to:

- [x] Parameterize environment values in `docker-compose.yml`
- [x] Use volumes, rather than bind mounts, for DB persistence
- [x] Provide an `env.template` that can be renamed to `.env`
- [x] Update instructions

**Comment by sajith** [comment]
PR #131 addresses these.
